<?php

/**
 * Created by IntelliJ IDEA.
 * User: vjcspy
 * Date: 10/27/15
 * Time: 5:13 PM
 */
class SM_XReport_Block_Adminhtml_Dashboard_Top extends Mage_Adminhtml_Block_Dashboard_Tab_Products_Ordered {
    public function __construct() {
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->_prepareCollection();
    }

    protected function _prepareCollection() {
        if (!Mage::helper('core')->isModuleEnabled('Mage_Sales')) {
            return $this;
        }
        if ($this->getParam('website')) {
            $storeIds = Mage::app()->getWebsite($this->getParam('website'))->getStoreIds();
            $storeId = array_pop($storeIds);
        } else if ($this->getParam('group')) {
            $storeIds = Mage::app()->getGroup($this->getParam('group'))->getStoreIds();
            $storeId = array_pop($storeIds);
        } else {
            $storeId = (int)$this->getParam('store');
        }

        $collection = Mage::getModel('xreport/resource_sales_report_bestsellers_collection')
            ->setModel('catalog/product')
            ->addStoreFilter($storeId);

        $this->setCollection($collection);

        return parent::_prepareCollection(); // TODO: Change the autogenerated stub
    }


}
