<?php
/**
 * Created by IntelliJ IDEA.
 * User: vjcspy
 * Date: 10/27/15
 * Time: 4:02 PM
 */
$this->setDataRow('quantity');
$dataQuantityChart = json_encode($this->getDataSalesChart('24h'));
$a = 1;
?>
<div class="panel panel-default" ng-controller="quantityController">
    <div class="panel-heading">
        <i class="fa fa-bar-chart-o fa-fw"></i> Quantity Overview - <label>//quantityTile.periodTitle//</label>

        <div class="pull-right hidden">
            <div class="btn-group">
                <button type="button" class="btn btn-default btn-xs dropdown-toggle"
                        data-toggle="dropdown">
                    Period
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu pull-right" role="menu">
                    <li ng-click="changePeriod(0);"><a class="">Last 24h</a>
                    </li>
                    <li ng-click="changePeriod(1);"><a>Last 7 days</a>
                    </li>
                    <li ng-click="changePeriod(2);"><a>Current Month</a>
                    </li>
                    <li class="divider"></li>
                    <li ng-click="changePeriod(3);"><a>YTD</a>
                    </li>
                    <li ng-click="changePeriod(4);"><a>2YTD</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body" ng-init='dashboadData.dataQuantityChart = <?php echo $dataQuantityChart; ?>'>
        <div class="row">
            <div class="col-lg-4">
                <div class="table-responsive">
                    <table ng-table="customConfigParams"
                           class="table table-condensed table-bordered table-striped">
                        <tr ng-repeat="row in $data">
                            <td data-title="'Date'">//row.label//</td>
                            <td data-title="'Qty'">//row.qty//</td>
                        </tr>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.col-lg-4 (nested) -->
            <div class="col-lg-8">
                <!--                                <div id="morris-bar-chart"></div>-->
                <canvas id="bar" class="chart chart-bar"
                        chart-data="quantityOverview.dataItem" chart-labels="quantityOverview.labelsItem">
                </canvas>
            </div>
            <!-- /.col-lg-8 (nested) -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.panel-body -->
</div>
