<?php
/**
 * Created by IntelliJ IDEA.
 * User: vjcspy
 * Date: 11/2/15
 * Time: 11:12 AM
 */
?>

<div ng-controller="salesHistoryCtrl">


    <iz-filter-container iz-datatable="dataTable.salesHistory"
                         iz-data-column-index='index = [
            {columnId: "increment_id", name: "#", show: true, filterType: "text", filterChecked: false},
            {columnId: "created_at", name: "Date", show: true,filterType: "dateRange", filterChecked: true},
            {columnId: "status", name: "Status", show: true,filterType: "select", filterChecked: false,dataSelect:<?php echo $this->getArrayOrderStatusForSelect() ?>},
            {columnId: "shipping_method", name: "Shipping method", show: false,filterType: "select", filterChecked: false,dataSelect:<?php echo Mage::helper('xreport')->getAllShippingMethods() ?>},
            {columnId: "shipping_amount", name: "Shipping amount", show: true,filterType: "text", filterChecked: false},
            {columnId: "method", name: "Payment method", show: true,filterType: "select", filterChecked: false,dataSelect:<?php echo Mage::helper('xreport')->getActivePaymentMethods() ?>},
            {columnId: "base_subtotal", name: "Total", show: true,filterType: "text", filterChecked: false},
            {columnId: "base_subtotal_refunded", name: "Subtotal refunded", show: false,filterType: "text", filterChecked: false},
            {columnId: "discount_amount", name: "Discount", show: false,filterType: "text", filterChecked: false},
            {columnId: "shipping_tax_amount", name: "Shipping tax", show: false,filterType: "text", filterChecked: false},
            {columnId: "shipping_tax_refunded", name: "Shipping tax refunded", show: false,filterType: "text", filterChecked: false},
            {columnId: "shipping_refunded", name: "Shipping refunded", show: false,filterType: "text", filterChecked: false},
            {columnId: "total_qty_ordered", name: "Total qty", show: false,filterType: "text", filterChecked: false},
            {columnId: "total_refunded", name: "Total refunded", show: false,filterType: "text", filterChecked: false},
            {columnId: "order_currency_code", name: "Currency", show: true,filterType: "select", filterChecked: false,dataSelect:<?php echo $this->getArrayCurrencyCodeForSelect() ?>},
            {columnId: "customer_email", name: "Customer Email", show: false,filterType: "text", filterChecked: false},
            {columnId: "store_name", name: "Store", show: true,filterType: "select", filterChecked: false,dataSelect:<?php echo $this->getArrayStoreForSelect() ?>},
            {columnId: "sku", name: "Sku", show: "alwayFalse",filterType: "text", filterChecked: false}
    ]'
                         iz-data-table-init-column="dataTable.salesHistoryInitColumn">
        <iz-filter-control>
            <iz-filter-controller-elem></iz-filter-controller-elem>
        </iz-filter-control>
        <iz-filter-action></iz-filter-action>
    </iz-filter-container>


    <!-- /.row -->
    <div class="row" style="padding-bottom: 50px">
        <div class="col-lg-12">
<!--            <div class="panel panel-default">-->
                <!-- /.panel-heading -->
<!--                <div class="panel-body">-->
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover full-min-width"
                               id="salesHistoryTable">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Date</th>
                                <th>Status</th>
                                <th>Shipping method</th>
                                <th>Shipping amount</th>
                                <th>Payment method</th>
                                <th>Total</th>
                                <th>Subtotal refunded</th>
                                <th>Discount</th>
                                <th>Shipping tax</th>
                                <th>Shipping tax refunded</th>
                                <th>Shipping refunded</th>
                                <th>Total qty</th>
                                <th>Total refunded</th>
                                <th>Currency</th>
                                <th>Customer email</th>
                                <th>Store name</th>
                                <th>Sku</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Total</th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.table-responsive -->
<!--                </div>-->
                <!-- /.panel-body -->
<!--            </div>-->
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>
