<?php
/**
 * Created by IntelliJ IDEA.
 * User: vjcspy
 * Date: 11/2/15
 * Time: 11:12 AM
 */
?>

<div ng-controller="salesHistoryCtrl">


    <iz-filter-container iz-datatable="dataTable.salesHistory"
                         iz-data-column-index='index = [
            {columnId: "name", name: "Name", show: true,filterType: "text", filterChecked: false},
            {columnId: "sku", name: "Sku", show: true,filterType: "text", filterChecked: false},
            {columnId: "price", name: "Price", show: false,filterType: "text", filterChecked: false},
            {columnId: "sum_qty", name: "Items Ordered", show: true,filterType: "text", filterChecked: false},
            {columnId: "sum_total", name: "Total", show: true,filterType: "text", filterChecked: false},
            {columnId: "sum_invoiced", name: "Invoiced", show: true,filterType: "text", filterChecked: false},
            {columnId: "sum_refunded", name: "Refunded", show: true,filterType: "text", filterChecked: false},
            {columnId: "cost", name: "Product Cost", show: false,filterType: "text", filterChecked: false},
            {columnId: "discount_amount", name: "Discount Amount", show: true,filterType: "text", filterChecked: false},
            {columnId: "item_qty", name: "Qty", show: true,filterType: "text", filterChecked: false},
            {columnId: "esitmation_data", name: "Out of Stock Estimate", show: true,filterType: "text", filterChecked: false},
            {columnId: "created_at", name: "Date", show: "alwayFalse",filterType: "dateRange", filterChecked: true},
    ]'
                         iz-data-table-init-column="dataTable.salesHistoryInitColumn">
        <iz-filter-control>
            <iz-filter-controller-elem></iz-filter-controller-elem>
        </iz-filter-control>
        <iz-filter-action></iz-filter-action>
    </iz-filter-container>


    <!-- /.row -->
    <div class="row" style="padding-bottom: 50px">
        <div class="col-lg-12">
            <!--            <div class="panel panel-default">-->
            <!-- /.panel-heading -->
            <!--                <div class="panel-body">-->
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover full-min-width"
                       id="salesHistoryTable">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Sku</th>
                        <th>Price</th>
                        <th>Items Ordered</th>
                        <th>Total</th>
                        <th>Invoiced</th>
                        <th>Refunded</th>
                        <th>Product Cost</th>
                        <th>Discount Amount</th>
                        <th>Qty</th>
                        <th>Out of Stock Estimate</th>
                        <th>Date</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>Total</th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                    </tfoot>
                </table>
            </div>
            <!-- /.table-responsive -->
            <!--                </div>-->
            <!-- /.panel-body -->
            <!--            </div>-->
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>
